spring:
  application:
    name: life-diary
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.data.mongodb: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
    com.lifediary: ${LOG_LEVEL:INFO}